apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template: 
    metadata:          
      labels:
        app: {{ .Release.Name }}-api
    spec:            
      containers:
      - name: api
        image: {{ .Values.api.image }}
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-api-configmap
        env:
          - name: Mongo__User
            valueFrom: 
              secretKeyRef:
                key: MONGO_INIT_ROOT_USERNAME
                {{- if empty .Values.mongodb.existSecret }}
                name: {{ .Release.Name }}-mongo-secret  
                {{- else }}
                name: {{ .Values.mongodb.existSecret }}
                {{- end}}
          - name: Mongo__Password
            valueFrom: 
              secretKeyRef:
                key: MONGO_INIT_ROOT_PASSWORD
                {{- if empty .Values.mongodb.existSecret }}
                name: {{ .Release.Name }}-mongo-secret  
                {{- else }}
                name: {{ .Values.mongodb.existSecret }}
                {{- end}}