apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-configmap
data:
  Mongo__Host: {{ template "mongodb.serviceName" . }}
  Mongo__DataBase: {{ .Values.mongodb.Database }}-mongo-service