apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: rafaferreira011/conversao-temperatura:v1
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec: 
  selector:
    app: conversao-temperatura
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
  type: NodePort