apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops2
spec:
  containers:
  - image: nginx
    name: giropops
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
