apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-veronez-net-cert
spec:
  secretName: veronez-net-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "maferreira94.shop"