apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: init
          image: kubedevio/ubuntu-curl:v1
          command: ["curl", "-X", "POST", "http://pruu.herokuapp.com/dump/initcontainer"]
      containers:
      - name: nginx
        image: nginx
        lifecycle:
          postStart:
            exec:
              command:
                - "curl"
                - "-X"
                - "POST"
                - "http://pruu.herokuapp.com/dump/lifecyclestart"
          preStop:
            exec:
              command:
                - "curl"
                - "-X"
                - "POST"
                - "http://pruu.herokuapp.com/dump/lifecyclestart"
        resources:
          limits:
            cpu: "500m"
            memory: 32Mi
        ports:
        - containerPort: 80
