apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
spec:
  rules:
  {{- range .Values.api.ingress }}
  - host: {{ . }}
    http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          serviceName: {{ $.Release.Name}}-api-service
          servicePort: 80
  {{- end }}
    