apiVersion: v1
kind: Pod
metadata:
  name: meu-pod
  labels:
    name: container-1
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
    - name: container-2
      image: redis
      command:
        - redis-server
        - "/redis-master/redis.conf" 
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 6379  
      volumeMounts:
        - name: workdir
          mountPath: /tmp/
    - name: container-3
      image: busybox
      command: ["sh", "-c", "echo 'giropops' > /tmp/toska"] 
      volumeMounts:
        - name: workdir
          mountPath: /tmp/
volumes:
  - name: workdir
    emptyDir: {}
