apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://10.0.242.163:8200"
      path: "linuxtips"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-policy-token"
          key: "token"