apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linuxtips-senhas
    creationPolicy: Owner
  data:
  - secretKey: palavra1
    remoteRef:
      key: linuxtips/senha
      property: palabra1